[template-aliases]
# todo: switch to commit trailers
default_commit_description = '''
surround("\n\n", "\n", config("custom.coauthors").as_string_list().map(|author| "Co-Authored-By: " ++ author).join("\n"))
'''

[aliases]
team = [
  'util',
  'exec',
  'sh',
  '--',
  '-c',
  '''
	set -euo pipefail

	coauthorsfile="$(dirname $(jj config path --user | head -n1))/coauthors.json"
	# test -f "$coauthorsfile" || echo '{}' > "$coauthorsfile"

	if [[ $# -eq 0 ]]; then
		jj config list --color never | rg '^custom.coauthors = ' | head -n1 | cut -d= -f2 | jq --raw-output .[]
		exit 0
	fi
	if [[ "$1" == "--help" || "$1" == "-h" ]]; then
		echo "jj team alias1 alias2"
		echo "jj team # show current"
		echo "jj team disable"
		exit 0
	fi
	if [[ "$1" == "list" ]]; then
		jq '.' "$coauthorsfile"
		exit 0
	fi
	if [[ "$1" == "disable" ]]; then
		jj config set --user custom.coauthors "[]"
		exit 0
	fi

	coauthors=$(jq --compact-output '. as $coauthors | $ARGS.positional | map($coauthors[.])' "$coauthorsfile" --args "$@")
	jj config set --user custom.coauthors "$coauthors"
	echo "$coauthors" | jq --raw-output .[]
''',
  '',
]
