[[contacts]]
|||||||||||wknkrrqk 93798023 "local: context7 api key" (parents of squashed revision)===========name = "(devneo) U1"
numbers = ["051136059299"]
[[contacts]]
=======name = "(devneo) U1"
numbers = ["051136059299"]
[[contacts]]
name = "(devneo) U1"
numbers = ["051136059299"]

[[contacts]]
name = "(devneo) Voiza 1"
numbers = ["051136059291"]

[[contacts]]
name = "(devneo) Voiza 2"
numbers = ["051136059292"]

[[contacts]]
name = "(devneo) Voiza 3"
numbers = ["051136059293"]
